### ISSUE TITLE
possible error in dep library

### ISSUE THREAD

**Issue by rttomlinson** [rttomlinson/spotify-record-player#2]
WARNING: zbar/decoder/databar.c:1249: _zbar_decode_databar: Assertion "seg->finder >= 0" failed.
	i=7 f=-1(111) part=0
^CTraceback (most recent call last):
  File "barcode_scanner_video.py", line 157, in <module>
    finally:
  File "barcode_scanner_video.py", line 144, in start_video_stream
    cv2.destroyAllWindows()
KeyboardInterrupt

**Comment by John-Jood** [comment]
Hi did you manage to find the solution ? I face the same problem

**Comment by rttomlinson** [comment]
I haven't looked at it in a little bit. I'll probably spend some time this week.
If I can't figure it out in the `zbar` lib, I'll just handle the exception and restart the process with the old player state.
Are you running into the issue in this project or something else you're working on?

**Comment by John-Jood** [comment]
No i'm facing this issue on another project : [https://github.com/Kienz/dinoqode](url). It's a kid friendly Sonos player based on Spotify among other music platforms. It works with QrCode cards > Scanned with a PI Camera thanks to Zbar > Link is send to [https://github.com/jishi/node-sonos-http-api](url) wich launch the right music on Spotify through my Sonos System.

While everything works fine for some time, after several scans i get this problem.
